### ISSUE TITLE
Relative links

### ISSUE THREAD

**Issue by hoclun-rigsep** [Flamenco/stackeditpro#11]
Would be cool if these were followed within StackEditPro!

**Comment by Flamenco** [comment]
I am almost certain relative links work in certain scenarios, because the refactoring tool will pull out blocks and replace them with a link. .

<img width="426" alt="Screen Shot 2022-03-30 at 4 28 29 PM" src="https://user-images.githubusercontent.com/819940/160925376-461e44a2-84f3-4b63-8ed5-b43b26adb512.png">


<img width="313" alt="Screen Shot 2022-03-30 at 4 30 48 PM" src="https://user-images.githubusercontent.com/819940/160925517-ad616e21-993d-46f4-809a-a928806d4495.png">

<img width="539" alt="Screen Shot 2022-03-30 at 4 28 55 PM" src="https://user-images.githubusercontent.com/819940/160925534-d974eb78-2edf-4d21-b518-1a143f7ab012.png">

<img width="556" alt="Screen Shot 2022-03-30 at 4 29 25 PM" src="https://user-images.githubusercontent.com/819940/160925558-8323ab51-d77d-42dd-9cc8-57b58135f718.png">

**Comment by Flamenco** [comment]
Perhaps the link only works on GitHub pages.  It has been a long time since I used that feature.

**Comment by Flamenco** [comment]
Replace `main` with `app` in your link, and the relative link will work.

For example.
```
See [Hello World](/app#id=uoaZPvKvefEqy8Ui)
```

**Comment by hoclun-rigsep** [comment]
I don't consider that a relative link!

**Comment by Flamenco** [comment]
Why, because it uses an id instead of a path?  Can you even address a single page on stackedit.io?  You can use relative links when you *publish* pages.

**Comment by hoclun-rigsep** [comment]
Because to me relative link means something like "filesystem-based path relative to the file in which the link appears", and that's what it means in other contexts like for example GitHub (or just any filesystem-based web server context), where

```markdown
- Submit questions to Chief Esposito. Gather them [here](questions.md).
```

will render a link to `questions.md` in the same directory. The id-based link suggested above has no meaning outside of StackEditPro.

One can of course just navigate to the target using the tree view on the left-hand side of StackEditPro's UI; I thought it might be nice if one could also click on the link in the preview pane.
